services:
  db:
    build: ./db
    restart: always
    networks: 
        - network
    ports:
        - '5432:5432'
  app:
    build: .
    depends_on:
        - db
    networks:
        - network
    ports:
        - 8080:8080
networks:
    network: